pipeline {
agent any

```
environment {
    AWS_DEFAULT_REGION = "ap-south-1"
    TF_ENV = "dev"
}

stages {

    stage('Checkout Code') {
        steps {
            git branch: 'main',
                url: 'https://github.com/<your-username>/<your-repo>.git'
        }
    }

    stage('Terraform Init') {
        steps {
            withCredentials([[
                $class: 'AmazonWebServicesCredentialsBinding',
                credentialsId: 'aws-terraform-creds'
            ]]) {
                sh '''
                cd dev
                terraform init -reconfigure
                '''
            }
        }
    }

    stage('Terraform Validate') {
        steps {
            sh '''
            cd dev
            terraform validate
            '''
        }
    }

    stage('Terraform Plan') {
        steps {
            withCredentials([[
                $class: 'AmazonWebServicesCredentialsBinding',
                credentialsId: 'aws-terraform-creds'
            ]]) {
                sh '''
                cd dev
                terraform plan -out=tfplan
                '''
            }
        }
    }

    stage('Terraform Apply') {
        steps {
            input message: "Do you want to apply Terraform changes?"
            withCredentials([[
                $class: 'AmazonWebServicesCredentialsBinding',
                credentialsId: 'aws-terraform-creds'
            ]]) {
                sh '''
                cd dev
                terraform apply -auto-approve tfplan
                '''
            }
        }
    }
}

post {
    success {
        echo "Terraform deployment completed successfully"
    }
    failure {
        echo "Terraform deployment failed"
    }
}
```

}
